# Generated by Django 4.2.5 on 2023-10-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_complaint_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incart',
            name='amount',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
